{"token_type":"Bearer","expires_at":1664734067,"expires_in":21155,"refresh_token":"bfb54d055b2b615e5b561c05f806661f05857330","access_token":"880f74323a602f806ea196e7a84dc3a4b4c11514","athlete":{"id":108854991,"username":null,"resource_state":2,"firstname":"Franklin","lastname":"Kirby","bio":null,"city":"Oklahoma City","state":"Oklahoma","country":"United States","sex":"M","premium":false,"summit":false,"created_at":"2022-09-30T08:12:06Z","updated_at":"2022-09-30T08:16:39Z","badge_type_id":0,"weight":0.0,"profile_medium":"https://dgalywyr863hv.cloudfront.net/pictures/athletes/108854991/25671547/1/medium.jpg","profile":"https://dgalywyr863hv.cloudfront.net/pictures/athletes/108854991/25671547/1/large.jpg","friend":null,"follower":null}}